apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-java-k8s
  namespace: ns-java-k8s
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-java-k8s
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
